### ISSUE TITLE
opencv is not finding libXext.so.6

### ISSUE THREAD

**Issue by rsignell-usgs** [ESIPFed/esiphub-dev#13]
@dbuscombe-usgs needs `opencv` for the USGS CDI workshop on deep learning, and after installing from `conda-forge`, we are getting: 
```python-traceback
ImportError                               Traceback (most recent call last)
<ipython-input-1-c8ec22b3e787> in <module>()
----> 1 import cv2

ImportError: libXext.so.6: cannot open shared object file: No such file or directory
```
when we installed `opencv`, we got this, which looked okay to me:
```
jovyan@jupyter-rsignell-2dusgs:~$ conda install opencv
Solving environment: done

## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - opencv


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libwebp-0.5.2              |                7         688 KB  conda-forge
    jasper-1.900.1             |                4         275 KB  conda-forge
    scipy-1.1.0                |py36_blas_openblas_200        40.2 MB  conda-forge
    openblas-0.2.20            |                8        17.0 MB  conda-forge
    blas-1.1                   |         openblas           1 KB  conda-forge
    graphite2-1.3.11           |                0         119 KB  conda-forge
    x264-20131218              |                0         4.9 MB  conda-forge
    opencv-3.4.1               |py36_blas_openblas_200        43.6 MB  conda-forge
    numpy-1.14.5               |py36_blas_openblash24bf2e0_200         9.0 MB  conda-forge
    harfbuzz-1.7.6             |                0         5.6 MB  conda-forge
    ffmpeg-3.2.4               |                3        58.1 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       179.5 MB

The following NEW packages will be INSTALLED:

    blas:      1.1-openblas                 conda-forge
    ffmpeg:    3.2.4-3                      conda-forge
    graphite2: 1.3.11-0                     conda-forge
    harfbuzz:  1.7.6-0                      conda-forge
    jasper:    1.900.1-4                    conda-forge
    libwebp:   0.5.2-7                      conda-forge
    openblas:  0.2.20-8                     conda-forge
    opencv:    3.4.1-py36_blas_openblas_200 conda-forge [blas_openblas]
    x264:      20131218-0                   conda-forge

The following packages will be UPDATED:

    numpy:     1.14.2-py36hdbf6ddf_1        defaults    --> 1.14.5-py36_blas_openblash24bf2e0_200 conda-forge [blas_openblas]
    scipy:     1.1.0-py36hfc37229_0         defaults    --> 1.1.0-py36_blas_openblas_200          conda-forge [blas_openblas]

Proceed ([y]/n)? y
```

**Comment by rsignell-usgs** [comment]
@ocefpaf, I guess this has something to do with [blas_openblas] ?

**Comment by rsignell-usgs** [comment]
Instead of adding this after the environment is already built, I tried adding it with all the other packages in the [Dockerfile](https://github.com/rsignell-usgs/helm-chart/blob/conda-forge/docker-images/notebook/Dockerfile) hoping that a one-shot specification of the packages would fix the issue, but I still got the same problem when I logged into the container with:
```
docker run -it pangeo-notebook /bin/bash
```
started python and tried `import cv2`.    😞

**Comment by ocefpaf** [comment]
> @ocefpaf, I guess this has something to do with [blas_openblas] ?

Nope. That change later is `conda` wonkiness b/c of its poor solver and channel preference features.

`libXext.so.6` is an X11 thing and we usually expected it to be present in the user machine, but most docker images, because they are not designed for display, don't have it. You can try to install the X11 stuff on the image using the system package manager or get the `xorg` packages from conda-forge. My guess is that you'll need at least `xorg-libxext`.

Note that we don't depended on the `xorg` packages present on conda-forge b/c it is usually recommended to rely on those present in the user machine. Also, I never tested our `xorg` packages with `openvc`.

**Comment by rsignell-usgs** [comment]
Thanks yet again to help from @ocefpaf I was able to get this going by installing the `libxext6` and `libgl1-mesa-glx` system libs into our [pangeo-notebook Dockerfile](https://github.com/rsignell-usgs/helm-chart/blob/conda-forge/docker-images/notebook/Dockerfile#L5-L6).   

@dbuscombe-usgs, please give http://pangeo.esipfed.org another try with your `opencv` workflow and please report back.

**Comment by ddbuscombe** [comment]
Yes, this now works. Thanks
