### ISSUE TITLE
Best way to implement interactive drawing in Notebook?

### ISSUE THREAD

**Issue by rsignell-usgs** [ESIPFed/esiphub-dev#15]
For his deep learning workshop, @dbuscombe-usgs needs the user to be able to draw polylines on an image and capture the pixel coordinates for further use in the Notebook.   

@ocefpaf suggests trying matplotlib  `plt.imshow` and `plt.ginput`, using `%matplotlib notebook` instead of the usual `%matplotlib inline`.

**Comment by ddbuscombe** [comment]
Thanks for the suggestion but using ginput is not viable because you can't draw freeform lines, like you can using opencv and callback functions

Besides, using ```%matplotlib notebook```, I get ```JavaScript output is disabled in JupyterLab``` errors

**Comment by rsignell-usgs** [comment]
So ginput is perhaps a no go because of limited functionality, but on the 2nd issue can you try using the notebook interface instead of jupyterlab to see if it works?

Just replace "lab" in the url to "tree", e.g.:
http://pangeo.esipfed.org/user/rsignell-usgs/tree
instead of 
http://pangeo.esipfed.org/user/rsignell-usgs/lab

**Comment by ocefpaf** [comment]
> Thanks for the suggestion but using ginput is not viable because you can't draw freeform lines, like you can using opencv and callback functions

I'm not familiar with `openvc` so I cannot comment on that. My guess is that it uses `matplotlib` under the hood so the figure interaction mechanism will be the same regardless of the extra functionality, like the free from drawing.

> Besides, using `%matplotlib notebook`, I get `JavaScript output is disabled in JupyterLab` errors.

JupyterLab changed everything and unfortunately a lot of old functionality is broken there. Also, I checked and the `ginput` functionality never worked with the interactive backend, so even the traditional notebook won't work :-(

See https://github.com/matplotlib/matplotlib/pull/6929

If you can activate a graphic display I recommend `%matplotlib tk` (or Qt, gtk, etc), but this is not trivial on cloud deployments.

I wonder if the JS based plotting libraries, like `bokeh`, `plotly`, etc, have this functionality. I'll investigate and report back.

**Comment by rsignell-usgs** [comment]
Thanks to help from @ocefpaf and @cbanek on [bokeh issues](https://github.com/bokeh/bokeh/pull/7686#issuecomment-402312641), this notebook [notebook to capture interactive drawing with bokeh](https://nbviewer.jupyter.org/gist/rsignell-usgs/dc4de1264b85ca762571e976f70b74e5) now works on the pangeo instance at pangeo.esipfed.org:

![2018-07-09_7-09-21](https://user-images.githubusercontent.com/1872600/42452108-226c75a0-8357-11e8-8b25-15351c18f6cd.png)

**Comment by ddbuscombe** [comment]
Hey thanks all, this looks great. I just tried to implement your example @rsignell-usgs in the pangeo.esipfed server but after ```output_notebook()``` I get

```Loading BokehJS ... JavaScript output is disabled in JupyterLab```

so nothing shows. Same result will all kernels. Any suggestions to show javascript outputs?

**Comment by rsignell-usgs** [comment]
@dbuscombe-usgs , can we use this form of interaction?  (not for tomorrow's workshop, OBVI)

@cbanek, what if we wanted to just draw a polyline on the screen instead of using the polygon selection tool?   Are we limited to the Bokeh selection tools?

**Comment by cbanek** [comment]
@rsignell-usgs I'm not sure what tool you're using to draw lines on the graph (if this is a bokeh thing, or a non-bokeh thing), although I'd be interested in learning more.  My PR to bokeh was to enable contacting the bokeh server from a notebook.  This means that you can use any of the fancy stuff that bokeh server allows, which also allows you to call arbitrary python back in your notebook cell and update the graphs.

**Comment by ddbuscombe** [comment]
@cbanek I'm essentially trying to replicate aspects of [this script](https://github.com/dbuscombe-usgs/dl_tools/blob/master/create_groundtruth/label_1image_crf.py) which currently uses opencv to allow users to annotate an image with the mouse. Free-form line drawing (not polygons). Not sure if this is possible within bokeh or not?

**Comment by ddbuscombe** [comment]
I could provide more details about how I'm using opencv, but it's essentially drawing windows with an image (using whatever the default graphical backend is) then using mouse callback functions to do the drawing

**Comment by rsignell-usgs** [comment]
@cbanek , so while the image annotation isn't  *currently* a bokeh thing, it seemed that bokeh would be the best candidate for allowing interactive drawing in a JupyterHub notebook, with coordinates returned to the notebook.   If you have other ideas of how we could accomplish this, please let us know!

**Comment by rsignell-usgs** [comment]
Closing as freehand drawing was implemented in https://github.com/bokeh/bokeh/pull/8147.

For usage see the freehand drawing section of  the [Earthsim Drawing Tools documentation](http://earthsim.pyviz.org/user_guide/Drawing_Tools.html).
