### ISSUE TITLE
pangeo.esipfed.org interface very slow

### ISSUE THREAD

**Issue by ddbuscombe** [ESIPFed/esiphub-dev#19]
Over the past few days the web interface http://pangeo.esipfed.org/ has been slow.  Today it is really slow. It often takes several minutes to start server, and load an .ipynb file. Having to close and restart several times.

**Comment by ddbuscombe** [comment]
So slow right now its unusable. 15 minutes to load a page. My internet connection is fast. Giving up for a while

**Comment by rsignell-usgs** [comment]
I just started my server and it came up in 30 seconds or so, and notebook came up and ran normally.  I wonder if you've used up all your disk space or something.  Can you start a new terminal and do a `df -h` to see?

**Comment by ddbuscombe** [comment]
I'm using 30% disk space. I've tried again and it is still slow, just loading one notebook. I'll try another network tomorrow

**Comment by rsignell-usgs** [comment]
Did you do “top”?
Did you try restarting your server?

-Rich

**Comment by ddbuscombe** [comment]
Thanks - yes I have restarted a few times. Top shows almost no resources used. But after loading a file for a few mins, it freezes completely. No idea, its weird

**Comment by rsignell-usgs** [comment]
Can you share your notebooks with me so I can try?

**Comment by ddbuscombe** [comment]
I think I figured it out. Basically, some of my notebooks are too large because tensorflow produces TONS of outputs and they remain in the notebook when executed. To try to counter this, I issue:

```
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
```
which filters out INFO logs, warnings, and errors, but still produces thousands of lines of ```stdout```. I could resort to using

```
%%capture
```

at the start of the cell but there is some useful info in all the output. I may just have to use a series of very small notebooks

**Comment by ddbuscombe** [comment]
I guess I could use

```
%%capture capt
%run myscript.py
```

then, if we want to view output

```
capt.stdout
```

?

**Comment by rsignell-usgs** [comment]
@ocefpaf, have you encountered this kind of problem with `stdout` in Jupyter and/or have any good ideas?

**Comment by ddbuscombe** [comment]
Looks like

```
capt.stdout
```

only captures the last line of the output

**Comment by ocefpaf** [comment]
> @ocefpaf, have you encountered this kind of problem with stdout in Jupyter and/or have any good ideas?

No, but I never tried anything like that. I'll give it a try and report back.

**Comment by ddbuscombe** [comment]
Just to clarify, one particular script I have (that I run using the ```%run``` magic command) generates tens of thousands of lines of output. I have reduced it as much as possible but most of it comes from low-level c++ routines. 

Using ```%%capture``` is working well, except that I would like to be able to see the last "N" lines of output. I thought I'd be able to pass ```capt.stdout```  to a file then use ```tail``` to view, but it appears ```capt.stdout``` only captures the last line, I guess because most of it wasn't being generated by the python script, by by lower-level calls

**Comment by ddbuscombe** [comment]
Update: this works well, using the bash magic command

```
%%bash -s "$var1" "$var2"
python myscript.py --flag1 $1 --flag2 $2 &> output.txt
```

**Comment by ocefpaf** [comment]
I was going to suggest the `bash` magic, if the problem can be platform dependent, or a thin wrapper that would save the stdout to a file.

**Comment by rsignell-usgs** [comment]
Hurrah for bash cell magic!    Okay to close @dbuscombe-usgs ?

**Comment by ddbuscombe** [comment]
Yep, case closed
