### ISSUE TITLE
New issue with importing opencv

### ISSUE THREAD

**Issue by ddbuscombe** [ESIPFed/esiphub-dev#24]
@rsignell-usgs it appears the python bindings to opencv no longer work.

```
python -c "import cv2"
```

returns

```
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

**Comment by rsignell-usgs** [comment]
@ocefpaf, the docker container we are using was built exclusively from the `conda-forge` channel 11 days ago.   Do you think rebuilding it would fix the problem?

**Comment by rsignell-usgs** [comment]
@dbuscombe-usgs , ah I think I know how to fix.   I need to `sudo apt-get install` in the Dockerfile.

https://github.com/conda-forge/pygridgen-feedstock/issues/10#issuecomment-365914605

I'm rebuilding now and will let you know when it's ready to test again.

**Comment by rsignell-usgs** [comment]
@dbuscombe-usgs , it should be working now.
Please go to http://pangeo.esipfed.org/hub/home, stop your server, and then start it again.   
Note: it takes 5-10 minutes to start the server when an update like this has occurred.

**Comment by ddbuscombe** [comment]
works great, thanks @rsignell-usgs you are truly awesome!

**Comment by rsignell-usgs** [comment]
📆 + 🏫  ... 🤞
