### ISSUE TITLE
issue with rasterio package on http://pangeo.esipfed.org

### ISSUE THREAD

**Issue by scottyhq** [ESIPFed/esiphub-dev#25]
I'm running into an error importing the `rasterio` package on the current deployment of http://pangeo.esipfed.org :

`import rasterio`

```python
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-df51458539a9> in <module>()
      1 get_ipython().run_line_magic('matplotlib', 'inline')
----> 2 import rasterio
      3 import numpy as np
      4 import xarray as xr
      5 import matplotlib.pyplot as plt

/opt/conda/lib/python3.6/site-packages/rasterio/__init__.py in <module>()
     21             pass
     22 
---> 23 from rasterio._base import gdal_version
     24 from rasterio.drivers import is_blacklisted
     25 from rasterio.dtypes import (

ImportError: libncurses.so.6: cannot open shared object file: No such file or directory
```

**Comment by rsignell-usgs** [comment]
@scottyhq, grrr....  Okay, rebuilding container. 

Also, can you try out dev.pangeo.io?    It seems to be working there: 
![2018-10-31_3-44-47](https://user-images.githubusercontent.com/1872600/47773143-84d1b400-dcbf-11e8-9e76-37217935311d.jpg)

**Comment by rsignell-usgs** [comment]
@scottyhq, after a heroic morning of conda-forge debugging by @ocefpaf, we finally have pangeo.esipfed.org working with `rasterio` again.    This [Dockerfile](https://github.com/rsignell-usgs/helm-chart/blob/esipfed/docker-images/notebook/Dockerfile) was the one that finally worked!

Thanks for the heads up that things were broken!
