### ISSUE TITLE
How do I create a custom conda environment in JupyterHub?

### ISSUE THREAD

**Issue by rsignell-usgs** [ESIPFed/esiphub-dev#27]
To create a custom environment:

1. Ensure that `nb_conda_kernels` is installed in the base conda environment.   If it's not, ask the JupyterHub provider to include it!

2. In JupyterHub, edit your `~/.condarc` to specify a persisted directory (like `/home/jovyan/my-conda-envs` for your environments:
```yaml
channels:
  - conda-forge
envs_dirs:
  - /home/jovyan/my-conda-envs
```

3. Create your custom environment including the `ipykernel` package:
```
conda create   -n my_new_custom_env      my_package_1  my_package_2 ipykernel
```

Stop and start your server. 

You should now be able to see your custom env on the kernel pick list:
![2019-02-06_16-15-40](https://user-images.githubusercontent.com/1872600/52374193-a236bc80-2a2a-11e9-9425-a34963722e91.png)

**Comment by ColinTalbert** [comment]
Worked perfectly!

**Comment by dnowacki-usgs** [comment]
Thanks Rich! The create line should read:
`conda create -n my_custom_env my_package1 mypackage2 ipykernel`

**Comment by rsignell-usgs** [comment]
Thanks @dnoawcki-usgs!  Corrected above!
