### ISSUE TITLE
Fix DNS issue

### ISSUE THREAD

**Issue by rsignell-usgs** [ESIPFed/esiphub-dev#4]
It's a bit awkward using http://<38-characters>.us-west-2.elb.amazonaws.com/hub/home

**Comment by jreadey** [comment]
I've tried adding a CNAME to our hdfgroup DNS & installing a cert on the AWS load balancer.
In that case I'm able to access/log in to Jupyter Hub, but strangely the notebook and terminal is not responsive.  I mentioned it here: https://github.com/pangeo-data/pangeo/issues/71, but not clear how to deal with this.

Do you have anyone on your side that would like to take a look?

**Comment by rsignell-usgs** [comment]
The attempt to fix the DNS on friday seems to have left the hdflab.hdfgroup.org site broken:
https://hdflab.hdfgroup.org works, but if you try to open a terminal or a notebook, it can't connect

https://hdflab.hdfgroup.org/user/rsignell-usgs/terminals/1
https://hdflab.hdfgroup.org/user/jready/terminals/1

**Comment by rsignell-usgs** [comment]
https://hdflab.hdfgroup.org
and 
http://pangeo.esipfed.org 
are both working.
