### ISSUE TITLE
Modify base conda environment

### ISSUE THREAD

**Issue by rsignell-usgs** [ESIPFed/esiphub-dev#5]
The base conda environment is missing `nb_conda_kernels`, which would allow us to pick alternate kernels (environments) from Jupyter.  

It also might be helpful if the base environment included:
```
conda install xarray boto3 zarr s3fs nb_conda_kernels gcsfs nb_conda_kernels
```

**Comment by rsignell-usgs** [comment]
@jreadey , can you please add `nb_conda_kernels` to the base conda environment ASAP?

**Comment by jreadey** [comment]
Looking at this now.

gcsfs wouldn't make sense for an AWS deployment would it?

**Comment by rsignell-usgs** [comment]
Yes, even though we are on AWS, we want to be able to read data written by the pangeo instance on GCE onto GCS.

**Comment by jreadey** [comment]
Packages are installed.
Let me know if everything works for you.

**Comment by rsignell-usgs** [comment]
Yes!  It's working!  Woohoo!!!!

![2018-04-11_20-44-34](https://user-images.githubusercontent.com/1872600/38650368-7442e680-3dc9-11e8-800e-b0c2683cc191.jpg)
